kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: stable-diffusion-role
  namespace: {{namespace}}
rules:
  - verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
    apiGroups:
      - ''
    resources:
      - secrets
  - verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
    apiGroups:
      - serving.kserve.io
    resources:
      - servingruntimes
      - inferenceservices